### ISSUE TITLE
ValueError: Expected string. Got <type 'list'>

### ISSUE THREAD

**Issue by hakong** [opinkerfi/adagios#529]
I know I'm not supposed to edit this, but ...
![valueerror expected string got type list](https://cloud.githubusercontent.com/assets/4422113/6268297/947ac9ea-b843-11e4-8cc9-8d8b13fa753a.gif)
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/adagios/objectbrowser/views.py", line 219, in edit_object
    return _edit_service(request, c)
  File "/usr/lib/python2.6/site-packages/pynag/Utils/decorators.py", line 35, in wrap
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/adagios/objectbrowser/views.py", line 325, in _edit_service
    return render_to_response('edit_service.html', c, context_instance=RequestContext(request))
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/defaulttags.py", line 285, in render
    return nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/loader_tags.py", line 156, in render
    return self.render_template(self.template, context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/loader_tags.py", line 138, in render_template
    output = template.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/defaulttags.py", line 285, in render
    return nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/template/debug.py", line 87, in render
    output = force_text(output)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/utils/encoding.py", line 99, in force_text
    s = s.__unicode__()
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/forms/forms.py", line 411, in __str__
    return self.as_widget()
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/forms/forms.py", line 458, in as_widget
    return widget.render(name, self.value(), attrs=attrs)
  File "/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg/django/forms/forms.py", line 496, in value
    return self.field.prepare_value(data)
  File "/usr/lib/python2.6/site-packages/adagios/objectbrowser/forms.py", line 174, in prepare_value
    raise ValueError("Expected string. Got %s" % type(value))
ValueError: Expected string. Got <type 'list'>
```

**Comment by mayasd** [comment]
Hi,
I had this same problem after upgraded to Adagios 1.6.1. 
To fix problem, do a global commit on your nagios/shinken configuration. Like that : 

``` sh
cd /etc/shinken
sudo -H -u shinken git commit -a

sudo -H -u shinken git status                                  
# On branch master
nothing to commit, working directory clean
```

**Comment by hakong** [comment]
I suspect this is because the file im trying to edit is not in /etc/nagios, but /usr/share/okconfig. I know I shouldn't be editing this file. Maybe Adagios should warn you if you try to edit a file outside of the git repo?

**Comment by giner** [comment]
I've got just the same issue with a new installation of 1.6.1.

```
Traceback (most recent call last):
  File "/opt/adagios/lib/python2.7/site-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/opt/adagios/lib/python2.7/site-packages/adagios/objectbrowser/views.py", line 219, in edit_object
    return _edit_service(request, c)
  File "/opt/adagios/lib/python2.7/site-packages/pynag/Utils/__init__.py", line 1411, in wrap
    return func(*args, **kwargs)
  File "/opt/adagios/lib/python2.7/site-packages/adagios/objectbrowser/views.py", line 325, in _edit_service
    return render_to_response('edit_service.html', c, context_instance=RequestContext(request))
  File "/opt/adagios/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/loader_tags.py", line 155, in render
    return self.render_template(self.template, context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/loader_tags.py", line 137, in render_template
    output = template.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/opt/adagios/lib/python2.7/site-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/opt/adagios/lib/python2.7/site-packages/django/utils/encoding.py", line 100, in force_text
    s = s.__unicode__()
  File "/opt/adagios/lib/python2.7/site-packages/django/forms/forms.py", line 425, in __str__
    return self.as_widget()
  File "/opt/adagios/lib/python2.7/site-packages/django/forms/forms.py", line 475, in as_widget
    return widget.render(name, self.value(), attrs=attrs)
  File "/opt/adagios/lib/python2.7/site-packages/django/forms/forms.py", line 513, in value
    return self.field.prepare_value(data)
  File "/opt/adagios/lib/python2.7/site-packages/adagios/objectbrowser/forms.py", line 160, in prepare_value
    raise ValueError("Expected string. Got %s" % type(value))
ValueError: Expected string. Got <type 'list'>
```

**Comment by hakong** [comment]
Post the output of:
```
cd /etc/nagios
ls -la
git status
```

**Comment by giner** [comment]
```
# ls -la
total 152
drwxr-xr-x   6 root   root    4096 Mar  2 15:29 .
drwxr-xr-x 104 root   root    4096 Mar  2 12:14 ..
drwxr-xr-x   6 nagios nagios  4096 Mar  2 13:26 adagios
-rw-r--r--   1 root   root    1986 Jul 29  2011 apache2.conf
-rw-r--r--   1 root   root   12479 Jan  9  2014 cgi.cfg
-rw-r--r--   1 root   root    3185 Feb 27 13:52 commands.cfg
-rw-r--r--   1 root   root    2443 Jan  9  2014 commands.cfg.orig
drwxr-xr-x   2 root   root    4096 Mar  2 15:15 conf.d
drwxr-xr-x   8 nagios nagios  4096 Mar  2 15:30 .git
-rw-r--r--   1 root   root      50 Feb 26 14:51 htpasswd.users
-rw-r--r--   1 root   root   44917 Feb 26 22:28 nagios.cfg
-rw-r--r--   1 root   root   44703 Jan  9  2014 nagios.cfg.orig
-rw-r-----   1 root   nagios  1336 Feb 27 13:54 resource.cfg
-rw-r-----   1 root   nagios  1293 Jul 29  2011 resource.cfg.orig
drwxr-xr-x   2 root   root    4096 Feb 26 14:51 stylesheets
```
```
# git status
On branch master
nothing to commit, working directory clean
```

**Comment by hakong** [comment]
what file were you trying to edit?

**Comment by giner** [comment]
I have just found out that it was a permission issue. Adagios tried to modify /etc/nagios3/conf.d/services_nagios2.cfg and coud not (was owned by root) so generated this error.
This helped: ```chown nagios /etc/nagios3/conf.d/services_nagios2.cfg```. I think Adagios should generate clearer error messages in such cases.

**Comment by hakong** [comment]
I agree. @palli?

**Comment by mayasd** [comment]
@palli I think you can closed this issue ;)
