### ISSUE TITLE
REST interfaces failing

### ISSUE THREAD

**Issue by aerhakr** [opinkerfi/adagios#542]
Debian 7
Adagios 1.6.1-1

http://myhost/adagios/rest/status/json/acknowledge

POST through webUI gives:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/adagios/rest/views.py", line 112, in handle_request
    return HttpResponse(result, mimetype=mimetype)
  File "/usr/local/lib/python2.7/dist-packages/django/http/response.py", line 340, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'

CURL example dumps entire page instead of response, even tried setting application types.

**Comment by tomas-edwardsson** [comment]
It looks like you are using Django 1.7 which Adagios does not support yet, I would suggest you try running with django 1.6 instead and you will have a smoother ride.

I'm closing this ticket for now but feel free to re-open if you still have problems.

**Comment by aerhakr** [comment]
Yep, problem is resolved. My bad.
