### ISSUE TITLE
error saving a host

### ISSUE THREAD

**Issue by ryepup** [opinkerfi/adagios#559]
I edit a host, and then get a 500 with this message:

```
ValueError: Expected string. Got <type 'list'> 
```

Debug information:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/adagios/objectbrowser/views.py", line 225, in edit_object
    return _edit_host(request, c)
  File "/usr/local/lib/python2.7/dist-packages/pynag/Utils/decorators.py", line 35, in wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/adagios/objectbrowser/views.py", line 460, in _edit_host
    return render_to_response('edit_host.html', c, context_instance=RequestContext(request))
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 155, in render
    return self.render_template(self.template, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 137, in render_template
    output = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/encoding.py", line 100, in force_text
    s = s.__unicode__()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 425, in __str__
    return self.as_widget()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 475, in as_widget
    return widget.render(name, self.value(), attrs=attrs)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 513, in value
    return self.field.prepare_value(data)
  File "/usr/local/lib/python2.7/dist-packages/adagios/objectbrowser/forms.py", line 174, in prepare_value
    raise ValueError("Expected string. Got %s" % type(value))
ValueError: Expected string. Got <type 'list'>
```

I think this is caused by notification options. If I look at my form POST, I have:

```
notification_options=d&notification_options=u&notification_options=r&notification_options=f
```

That's getting parsed into python as `['d', 'u', 'r', 'f']`, and then `prepare_value` is not prepared to handle that value.

I'll make a pull request shortly.

**Comment by ryepup** [comment]
It looks like there's a test that asserts this exception is correct; maybe this is actually a django version or uwsgi vs gunicorn thing? Does this get POSTed differently for other people?

**Comment by mayasd** [comment]
Hi,
Have you seen this issue #529 ?

**Comment by ryepup** [comment]
@mayasd I did not see that, but I was getting this error on master after #533 was merged. I traced the error and it seemed to be a straightforward django deserialization bug.
