### ISSUE TITLE
Support for Nagios 4?

### ISSUE THREAD

**Issue by spicysomtam** [opinkerfi/adagios#585]
We installed Adagios following the instructions on the wiki. We originally tried to install it on centos 7.1, but had issues with adagios and reverted to centos 6.6. Because of the issues, we decided to follow the install instructions to the letter and installed Nagios 3. However, Nagios 3 is not being actively developed since there is version 4 and the question is: does adagios support Nagios 4? Over time we feel Nagios 3 will become buggy as its not updated to support later versions of Linux.

If it does support Nagios 4, can we have some documentation on the wiki? A good start would be upgrading to Nagios 4. Even better would be install guides for installing on Nagios 4, and active encouragement to install Nagios 4 rather than 3.

Thanks in advance.

**Comment by palli** [comment]
Adagios itself has no problems with Nagios 4 (since from adagios perspective they are identical). 

There is a problem that arises with some of the nagios extensions that adagios takes advantage of. For example:
* mk-livestatus (if you want status data)
* pnp4nagios (if you want graphs)

So far we have stuck to putting in our install guides that these extensions need to be up and running, and rely on the install guides for those specific projects (because it is hard for us to maintain documentation for the whole stack).

All that said, last time I check (about 12months or so ago), there were very few users of nagios4, and mk-livestatus had some basic problems which required patching nagios4, and nagios4 was not accepting those patches.

Usually I am not one to say which monitoring cores to use, but I believe for this reason many potential adopters of nagios4 have moved over to naemon, since it has mk-livestatus built in. Myself, I use nagios3 only because last time i check (again 12 months), it was the only one that works 'out of the box' using centos 6.x and epel yum repository.

**Comment by historicbruno** [comment]
At least mk-livestatus now supports Nagios 4 with no patches needed (I've tested 1.2.8b1 and 4.0.8, respectively). However, you may need to compile mk-livestatus yourself:
https://mathias-kettner.de/check_mk_werks.php?werk_id=0276&HTML=yes

The check-mk-livestatus and pnp4nagios packages currently available in CentOS 7 do not work, but I don't plan on using pnp4nagios.

Another issue is the CentOS 7 package for Nagios 4 doesn't support reloading the service, but again that works if you manually compile and install Nagios.

**Comment by djgreg13** [comment]
Maybe a change with downtimes 👍 
```
Traceback (most recent call last):
  File "/opt/adagios/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/opt/adagios/adagios/status/views.py", line 971, in downtime_list
    c['downtimes'] = l.query('GET downtimes', *args)
  File "/usr/local/lib/python2.7/dist-packages/pynag/Parsers/multisite.py", line 80, in query
    query_result = backend_instance.query(query, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pynag/Parsers/livestatus.py", line 996, in query
    raise InvalidResponseFromLivestatus(query=livestatus_query, response=response_data)
InvalidResponseFromLivestatus: Could not parse response from livestatus.
Query:GET downtimes
ResponseHeader: fixed16
OutputFormat: python
ColumnHeaders: on
```


```
InvalidResponseFromLivestatus: Could not parse response from livestatus. Query:GET downtimes ResponseHeader: fixed16 OutputFormat: python ColumnHeaders: on Response: [[u"author",u"comment",u"duration",u"end_time",u"entry_time",u"fixed",u"host_accept_passive_checks",u"host_acknowledged",u"host_acknowledgement_type",u"host_action_url",u"host_action_url_expanded",u"host_active_checks_enabled",u"host_address",u"host_alias",u"host_check_command",u"host_check_command_expanded",u"host_check_flapping_recovery_notification",u"host_check_freshness",u"host_check_interval",u"host_check_options",u"host_check_period",u"host_check_type",u"host_checks_enabled",u"host_childs",u"host_comments",u"host_comments_with_extra_info",u"host_comments_with_info",u"host_contact_groups",u"host_contacts",u"host_current_attempt",u"host_current_notification_number",u"host_custom_variable_names",u"host_custom_variable_values",u"host_custom_variables",u"host_display_name",u"host_downtimes",u"host_downtimes_with_info",u"host_event_handler",u"host_event_handler_enabled",u"host_execution_time",u"host_filename",u"host_first_notification_delay",u"host_flap_detection_enabled",u"host_groups",u"host_hard_state",u"host_has_been_checked",u"host_high_flap_threshold",u"host_icon_image",u"host_icon_image_alt",u"host_icon_image_expanded",u"host_in_check_period",u"host_in_notification_period",u"host_in_service_period",u"host_initial_state",u"host_is_executing",u"host_is_flapping",u"host_last_check",u"host_last_hard_state",u"host_last_hard_state_change",u"host_last_notification",u"host_last_state",u"host_last_state_change",u"host_last_time_down",u"host_last_time_unreachable",u"host_last_time_up",u"host_latency",u"host_long_plugin_output",u"host_low_flap_threshold",u"host_max_check_attempts",u"host_metrics",u"host_mk_inventory",u"host_mk_inventory_gz",u"host_mk_inventory_last",u"host_modified_attributes",u"host_modified_attributes_list",u"host_name",u"host_next_check",u"host_next_notification",u"host_no_more_notifications",u"host_notes",u"host_notes_expanded",u"host_notes_url",u"host_notes_url_expanded",u"host_notification_interval",u"host_notification_period",u"host_notifications_enabled",u"host_num_services",u"host_num_services_crit",u"host_num_services_hard_crit",u"host_num_services_hard_ok",u"host_num_services_hard_unknown",u"host_num_services_hard_warn",u"host_num_services_ok",u"host_num_services_pending",u"host_num_services_unknown",u"host_num_services_warn",u"host_obsess_over_host",u"host_parents",u"host_pending_flex_downtime",u"host_percent_state_change",u"host_perf_data",u"host_plugin_output",u"host_pnpgraph_present",u"host_process_performance_data",u"host_retry_interval",u"host_scheduled_downtime_depth",u"host_service_period",u"host_services",u"host_services_with_fullstate",u"host_services_with_info",u"host_services_with_state",u"host_staleness",u"host_state",u"host_state_type",u"host_statusmap_image",u"host_total_services",u"host_worst_service_hard_state",u"host_worst_service_state",u"host_x_3d",u"host_y_3d",u"host_z_3d",u"id",u"is_service",u"service_accept_passive_checks",u"service_acknowledged",u"service_acknowledgement_type",u"service_action_url",u"service_action_url_expanded",u"service_active_checks_enabled",u"service_cache_interval",u"service_cached_at",u"service_check_command",u"service_check_command_expanded",u"service_check_freshness",u"service_check_interval",u"service_check_options",u"service_check_period",u"service_check_type",u"service_checks_enabled",u"service_comments",u"service_comments_with_extra_info",u"service_comments_with_info",u"service_contact_groups",u"service_contacts",u"service_current_attempt",u"service_current_notification_number",u"service_custom_variable_names",u"service_custom_variable_values",u"service_custom_variables",u"service_description",u"service_display_name",u"service_downtimes",u"service_downtimes_with_info",u"service_event_handler",u"service_event_handler_enabled",u"service_execution_time",u"service_first_notification_delay",u"service_flap_detection_enabled",u"service_groups",u"service_has_been_checked",u"service_high_flap_threshold",u"service_icon_image",u"service_icon_image_alt",u"service_icon_image_expanded",u"service_in_check_period",u"service_in_notification_period",u"service_in_service_period",u"service_initial_state",u"service_is_executing",u"service_is_flapping",u"service_last_check",u"service_last_hard_state",u"service_last_hard_state_change",u"service_last_notification",u"service_last_state",u"service_last_state_change",u"service_last_time_critical",u"service_last_time_ok",u"service_last_time_unknown",u"service_last_time_warning",u"service_latency",u"service_long_plugin_output",u"service_low_flap_threshold",u"service_max_check_attempts",u"service_metrics",u"service_modified_attributes",u"service_modified_attributes_list",u"service_next_check",u"service_next_notification",u"service_no_more_notifications",u"service_notes",u"service_notes_expanded",u"service_notes_url",u"service_notes_url_expanded",u"service_notification_interval",u"service_notification_period",u"service_notifications_enabled",u"service_obsess_over_service",u"service_percent_state_change",u"service_perf_data",u"service_plugin_output",u"service_pnpgraph_present",u"service_process_performance_data",u"service_retry_interval",u"service_scheduled_downtime_depth",u"service_service_period",u"service_staleness",u"service_state",u"service_state_type",u"start_time",u"triggered_by",u"type"], [u"Nagios Admin",u"Test",7200,1493105678,1493098484,1,1,0,0,u"",u"",1,u"127.0.0.1",u"localhost",u"check-host-alive",u"check-host-alive",0,0,5.0000000000e+00,0,u"24x7",0,1,[],[5],[[5,u"Nagios Admin",u"This host has been scheduled for fixed downtime from 04-25-2017 07:34:38 to 04-25-2017 09:34:38. Notifications for the host will not be sent out during that time period.",2,1493098484]],[[5,u"Nagios Admin",u"This host has been scheduled for fixed downtime from 04-25-2017 07:34:38 to 04-25-2017 09:34:38. Notifications for the host will not be sent out during that time period."]],[u"admins"],[u"nagiosadmin"],1,0,[],[],{},u"localhost",[3],[[3,u"Nagios Admin",u"Test"]],u"",1,3.9990790000e+00,u"",0.0000000000e+00,1,[u"linux-servers"],0,1,0.0000000000e+00,u"",u"",u"",1,0,1,0,0,0,1493098367,0,1492469838,0,0,1492469838,0,0,1493098371,8.3600002108e-04,u"",0.0000000000e+00,10,[],"","",0,0,[],u"localhost",1493098671,0,0,u"",u"",u"",u"",1.2000000000e+02,u"workhours",1,8,0,0,8,0,0,8,0,0,0,1,[],0,0.0000000000e+00,u"rta=0.022000ms;3000.000000;5000.000000;0.000000 pl=0%;80;100;0",u"PING OK - Paquets perdus = 0%, RTA = 0.02 ms",-1,1,1.0000000000e+00,1,u"",[u"Total Processes",u"Swap Usage",u"SSH",u"Root Partition",u"PING",u"HTTP",u"Current Users",u"Current Load"],[[u"Total Processes",0,1,u"PROCS OK: 50 processus avec ETAT = RSZDT",0,1,4,0,0,1],[u"Swap Usage",0,1,u"SWAP OK - 98% libre (1335 MB sur un total de 1367 MB)",0,1,4,0,0,1],[u"SSH",0,1,u"SSH OK - OpenSSH_6.7p1 Debian-5+deb8u3 (protocol 2.0)",0,1,3,0,0,1],[u"Root Partition",0,1,u"DISK OK - free space: / 25814 MB (89% inode=94%):",0,1,4,0,0,1],[u"PING",0,1,u"PING OK - Paquets perdus = 0%, RTA = 0.02 ms",0,1,3,0,0,1],[u"HTTP",0,1,u"HTTP OK: HTTP/1.1 200 OK - 447 octets en 0,000 secondes de temps de r\u00e9ponse",0,1,4,0,0,1],[u"Current Users",0,1,u"UTILISATEURS OK - 0 utilisateurs actuellement connect\u00e9s sur",0,1,4,0,0,1],[u"Current Load",0,1,u"OK - Charge moyenne: 1.28, 0.58, 0.47",0,1,4,0,0,1]],[[u"Total Processes",0,1,u"PROCS OK: 50 processus avec ETAT = RSZDT"],[u"Swap Usage",0,1,u"SWAP OK - 98% libre (1335 MB sur un total de 1367 MB)"],[u"SSH",0,1,u"SSH OK - OpenSSH_6.7p1 Debian-5+deb8u3 (protocol 2.0)"],[u"Root Partition",0,1,u"DISK OK - free space: / 25814 MB (89% inode=94%):"],[u"PING",0,1,u"PING OK - Paquets perdus = 0%, RTA = 0.02 ms"],[u"HTTP",0,1,u"HTTP OK: HTTP/1.1 200 OK - 447 octets en 0,000 secondes de temps de r\u00e9ponse"],[u"Current Users",0,1,u"UTILISATEURS OK - 0 utilisateurs actuellement connect\u00e9s sur"],[u"Current Load",0,1,u"OK - Charge moyenne: 1.28, 0.58, 0.47"]],[[u"Total Processes",0,1],[u"Swap Usage",0,1],[u"SSH",0,1],[u"Root Partition",0,1],[u"PING",0,1],[u"HTTP",0,1],[u"Current Users",0,1],[u"Current Load",0,1]],4.4666666667e-01,0,1,u"",8,0,0,0.0000000000e+00,0.0000000000e+00,0.0000000000e+00,3,0,0,0,0,u"",u"",0,0,0,u"",u"",0,0.0000000000e+00,0,u"",0,0,[],[],[],[],[],0,0,[],[],{},u"",u"",[],[],u"",0,0.0000000000e+00,0.0000000000e+00,0,[],0,0.0000000000e+00,u"",u"",u"",0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000000000e+00,u"",0.0000000000e+00,0,,0,[],0,0,0,u"",u"",u"",u"",0.0000000000e+00,u"",0,0,0.0000000000e+00,u"",u"",0,0,0.0000000000e+00,0,u"",0.0000000000e+00,0,0,1493098478,0,2]]
```

**Comment by gardart** [comment]
Here is a new install guide for Adagios with Nagios 4 running on RHEL7 (livestatus and pnp4nagios are working as well)
https://github.com/opinkerfi/adagios/wiki/Install-guide
