### ISSUE TITLE
ControlError: Unable to detect daemon method, could not find initscript or systemd unit file

### ISSUE THREAD

**Issue by BizOps1** [opinkerfi/adagios#588]
Hello, I am completely new to Nagios and Adagios

After a reboot I received this. 

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/adagios/misc/views.py", line 203, in nagios_service
    nagios_bin=nagios_bin, nagios_cfg=nagios_cfg, nagios_init=nagios_init)
  File "/usr/lib/python2.6/site-packages/pynag/Control/__init__.py", line 73, in __init__
    self.method = self._guess_method()
  File "/usr/lib/python2.6/site-packages/pynag/Control/__init__.py", line 235, in _guess_method
    'Unable to detect daemon method, could not find init'
ControlError: Unable to detect daemon method, could not find initscript or systemd unit file

Please let me know if there is anything I can provide to help troubleshoot.

**Comment by BizOps1** [comment]
To add, 

This is a CentOS 6.6 box 

Fully updated.

**Comment by palli** [comment]
Did you install via yum repo ?

Any chance selinux is running and interfering ?

Try:
```
  setenforce 0
  service nagios restart
  service httpd restart
```

**Comment by BizOps1** [comment]
Fixed it by basically going through the install process again...
