### ISSUE TITLE
ParserError: "[Errno 2] No such file or directory while connecting to '/var/cache/naemon/live'. Make sure nagios is running and mk_livestatus loaded."

### ISSUE THREAD

**Issue by dyasny** [opinkerfi/adagios#600]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/adagios/status/views.py", line 650, in status_index
    c = adagios.status.utils.get_statistics(request)
  File "/usr/lib/python2.7/site-packages/adagios/status/utils.py", line 460, in get_statistics
    *arguments
  File "/usr/lib/python2.7/site-packages/pynag/Parsers/livestatus.py", line 1116, in get_services
    return self.query('GET services', *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pynag/Parsers/multisite.py", line 80, in query
    query_result = backend_instance.query(query, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pynag/Parsers/livestatus.py", line 973, in query
    livestatus_response = self.write(livestatus_query.get_query())
  File "/usr/lib/python2.7/site-packages/pynag/Parsers/livestatus.py", line 820, in write
    livestatus_socket = self._get_socket()
  File "/usr/lib/python2.7/site-packages/pynag/Parsers/livestatus.py", line 804, in _get_socket
    raise ParserError(msg % (e, self.livestatus_socket_path))
ParserError: "[Errno 2] No such file or directory while connecting to '/var/cache/naemon/live'. Make sure nagios is running and mk_livestatus loaded."

Steps to reproduce:
- install adagios by the install steps/script from the wiki on CentOS 7
- go into hosts and delete everything except for localhost (linksys, hp printers, winserver)
- watch the UI become unusable...

**Comment by dyasny** [comment]
any news on this issue?

**Comment by hakong** [comment]
The install instructions have been fixed.

Just remove mk-livestatus and install naemon-livestatus instead.

The old naemon config had the following in /etc/naemon/naemon.cfg:
```
broker_module=/usr/lib64/naemon/naemon-livestatus/livestatus.so /var/cache/naemon/live
```

but the new config has:
```
include_dir=module-conf.d
```

and in that folder there's livestatus.cfg that contains:

```
broker_module=/usr/lib64/naemon/naemon-livestatus/livestatus.so /var/cache/naemon/live
```

Be sure that you don't define it twice. Just uncomment it in the old config or put the .rpmnew one in place.

Check this post for more info about upgrading: https://2kswiki.wordpress.com/2016/06/14/upgrading-from-naemon-1-0-3-to-1-0-4/
