### ISSUE TITLE
Could not resolve commandline. Object not found

### ISSUE THREAD

**Issue by tombradford** [opinkerfi/adagios#649]
In the service information tab, I see the following:

```
Check command	Could not resolve commandline. Object not found
```

clicking edit service also produces the error message:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/adagios/objectbrowser/views.py", line 546, in bulk_edit
    for i in _querydict_to_objects(request):
  File "/usr/lib/python2.7/site-packages/adagios/objectbrowser/views.py", line 806, in _querydict_to_objects
    result.append(_find_service(host_name, service_description))
  File "/usr/lib/python2.7/site-packages/adagios/objectbrowser/views.py", line 822, in _find_service
    return result[0]
IndexError: list index out of range
```
here is a sample of my config setup:

```
define command {
    command_name    test_command
    command_line    $USER1$/test_command.py -H $HOSTADDRESS$
}

define hostgroup {
    hostgroup_name      hgrpA
    alias               Example hostgroup A
}

define host {
    use             hosttemplate
    address         X.X.X.X
    host_name       hostA
    alias           hostA
    hostgroups      hgrpA
    contact_groups  contactGroupsA
}

define host {
    check_period            24x7
    notification_interval   120
    notification_period     workhours
    check_command           check-host-alive
    name                    hosttemplate
    check_interval          5
    max_check_attempts      10
    notification_options    d,u,r
}

define service {
    service_description     test_service
    host_name               *, !hostB
    active_checks_enabled   1
    notification_interval   60
    notification_period     24x7
    passive_checks_enabled  1
    max_check_attempts      3
    notification_options    w,c,r,u
    check_period            24x7
    check_interval          5
    check_command           test_command
}
```
i have 100s of hosts in in the `hgrpA` hostgroup, all which produce the above error.

I can see the command if i use the nagios configuration tool (at `/nagios/cgi-bin/config.cgi?type=services`)

I'm using adagios v1.6.3 and nagios v4.4.3

Related issue: #177 

Any help would be much appreciated, thanks.

Tom

**Comment by gardart** [comment]
has this been fixed ?

**Comment by tombradford** [comment]
unfortunately not, the issue is still outstanding
