### ISSUE TITLE
Key Error on network parents

### ISSUE THREAD

**Issue by stestaz** [opinkerfi/adagios#663]
Hi,
I've an installation with more than 500 hosts, and when 500 hosts is exceeded the Network Parents section explode with this error

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/adagios/status/views.py", line 109, in network_parents
    i['child_hosts'].append(host_dict[x])
KeyError: u'xxx-ce-vg02'

the KeyError is the name of an host but this host is correctly configured and if I delete this host the error will appear with a new one.

This is a bug so please don't reply "maybe the host is missing"

**Comment by gardart** [comment]
thanks @palli I will update the documentation regarding the livestatus limit.

**Comment by tjyang** [comment]
- Same issue here for  instance over 500 hosts.

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/adagios/views.py", line 43, in wrapper
>     result = view_func(request, *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/adagios/status/views.py", line 108, in network_parents
>     i['child_hosts'].append(host_dict[x])
> KeyError: u'hostame.xxx.xxx'
> 
- live status and OS info.

> check-mk-livestatus-1.4.0p31-2.el7.x86_64
> CentOS Linux release 7.7.1908 (Core)
