### ISSUE TITLE
Adding host - service with same name

### ISSUE THREAD

**Issue by gummigudm** [opinkerfi/adagios#675]
Adding host without a template, results in a service of the same name as the host, being created.
Example can be seen under OK adagios host config for rt01.okhysing.is

**Comment by HJSK** [comment]
I had same, but little different : copy host from existing host, change Name & IP and got error : 
Should work when I copy a host which is already from 1 of the other hosts in NEMS. 

This is the error I got : 

Traceback (most recent call last):
  File "/opt/adagios/adagios/views.py", line 44, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/opt/adagios/adagios/objectbrowser/views.py", line 710, in copy_object
    f.save()
  File "/opt/adagios/adagios/objectbrowser/forms.py", line 595, in save
    tmp = self.pynag_object.copy(**self.cleaned_data)
  File "/opt/adagios/venv/lib/python3.9/site-packages/pynag/Model/__init__.py", line 1766, in copy
    copies = [ObjectDefinition.copy(self, recursive=recursive, filename=filename, **args)]
  File "/opt/adagios/venv/lib/python3.9/site-packages/pynag/Model/__init__.py", line 957, in copy
    new_object.save()
  File "/opt/adagios/venv/lib/python3.9/site-packages/pynag/Utils/decorators.py", line 22, in newFunction
    return f(*args, **kw)
  File "/opt/adagios/venv/lib/python3.9/site-packages/pynag/Model/__init__.py", line 798, in save
    self._event(level='pre_save', message="%s '%s'." % (self.object_type, self['shortname']))
  File "/opt/adagios/venv/lib/python3.9/site-packages/pynag/Model/__init__.py", line 1534, in _event
    i.pre_save(object_definition=self, message=message)
  File "/opt/adagios/venv/lib/python3.9/site-packages/pynag/Model/EventHandlers/__init__.py", line 219, in pre_save
    if self._is_dirty(filename):
  File "/opt/adagios/venv/lib/python3.9/site-packages/pynag/Model/EventHandlers/__init__.py", line 238, in _is_dirty
    output = self._run_command(command)
  File "/opt/adagios/venv/lib/python3.9/site-packages/pynag/Model/EventHandlers/__init__.py", line 173, in _run_command
    raise EventHandlerError(errorstring, errorcode=returncode, errorstring=stderr)
pynag.Model.EventHandlers.EventHandlerError: fatal: not a git repository (or any of the parent directories): .git
  
Further when want to make a notification to NEMSlinux (by button on same page below)

![NEMS page not found by making a  wish](https://github.com/opinkerfi/adagios/assets/24859934/5342b229-ecfb-4b2a-90ab-547be6f56d52)
