### ISSUE TITLE
RL8 Django 3 support ?  ModuleNotFoundError: No module named 'django.utils.six'

### ISSUE THREAD

**Issue by tjyang** [opinkerfi/adagios#677]
Hi 
I was to modify Makefile and adagio.spec files to compile el8 rpm for RockyLinux 8.7.
[status.py ](https://stackoverflow.com/questions/59524941/modulenotfounderror-no-module-named-django-utils-six)is still using django.utils.six.

google search shows[ in django3  django.utils.six  is deprecated.
](R1: https://github.com/opinkerfi/adagios/blob/master/adagios/status/utils.py#L36)
- error message

<details>
[me@va32lnagios03 ~]$ cat /etc/redhat-release
Rocky Linux release 8.7 (Green Obsidian)
[me@va32lnagios03~]$

[me@va32lnagios03~]$ rpm -qa |grep django
python-django3-bash-completion-3.2.19-1.el8.noarch
python3-django3-3.2.19-1.el8.noarch
[me@nagios03 ~]$

[me@nagios03~]$ python3 -m pdb /usr/lib/python3.6/site-packages/adagios/wsgi.py
> /usr/lib/python3.6/site-packages/adagios/wsgi.py(1)<module>()
-> import os
(Pdb) c
Traceback (most recent call last):
  File "/usr/lib64/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib64/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/lib64/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/adagios/wsgi.py", line 1, in <module>
    import os
  File "/usr/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python3.6/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.6/site-packages/adagios/bi/__init__.py", line 32, in <module>
    import adagios.status.utils
  File "/usr/lib/python3.6/site-packages/adagios/status/utils.py", line 36, in <module>
    import django.utils.six
ModuleNotFoundError: No module named 'django.utils.six'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/lib/python3.6/site-packages/adagios/status/utils.py(36)<module>()
-> import django.utils.six
(Pdb)
<details/>

**Comment by tjyang** [comment]
- I made a mistake to install python3-django3 instead of python3-django.
djangio3 support should be another effort to keep adagios up-to-date.
```
[me@nagios03 ~]$ python3 -m pdb /usr/lib/python3.6/site-packages/adagios/wsgi.py
> /usr/lib/python3.6/site-packages/adagios/wsgi.py(1)<module>()
-> import os
(Pdb) c
The program finished and will be restarted
> /usr/lib/python3.6/site-packages/adagios/wsgi.py(1)<module>()
-> import os
(Pdb) exit()
[tjyang@va32lnagios03t ~]$ date
Sun May 14 07:35:41 EDT 2023
[me@nagios03 ~]$

```

**Comment by tjyang** [comment]
- note to myself. a working adagio in python2 environment.  Can be used as a check point for pythyon3 porting effort.
```
[root@nagios01 httpd]# python  /usr/lib/python2.7/site-packages/adagios/manage.py  runserver 0.0.0.0:55534
Validating models...

0 errors found
May 14, 2023 - 08:22:59
Django version 1.6.11.7, using settings 'adagios.settings'
Starting development server at http://0.0.0.0:55534/
Quit the server with CONTROL-C.
[root@va32lnagios01 httpd]#

```
