### ISSUE TITLE
Migrating from centos 7 to rocky linux 9, cannot upgrade host

### ISSUE THREAD

**Issue by lazarobaca** [opinkerfi/adagios#687]
Hello

I migrate from:
Centos 7
Nagios 4.4.x
adagios 1.6.4

To 
Rocky linux 9
Naemon 1.4
adagios 2.0.2-1 (I installed from the wiki: https://github.com/opinkerfi/adagios/wiki/Install-guide#install-adagios-okconfig-and-naemon-on-red-hat-based-systems---rhel8--rhel9--centos-stream) 

Wnen I try to modify a host, it returns an error:

**ValueError: Expected string. Got <class 'list'>** 

and the raise error is:

Traceback (most recent call last):
  File "/opt/adagios/adagios/views.py", line 44, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/opt/adagios/adagios/objectbrowser/views.py", line 226, in edit_object
    return _edit_host(request, c)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/pynag/Utils/decorators.py", line 36, in wrap
    return func(*args, **kwargs)
  File "/opt/adagios/adagios/objectbrowser/views.py", line 460, in _edit_host
    return render_to_response('edit_host.html', c, context_instance=RequestContext(request))
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/shortcuts.py", line 43, in render_to_response
    content = loader.render_to_string(
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/loader.py", line 114, in render_to_string
    return engine.engine.render_to_string(
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/loader_tags.py", line 159, in render
    return template.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 212, in render
    return self._render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/template/debug.py", line 92, in render
    output = force_text(output)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/utils/encoding.py", line 90, in force_text
    s = six.text_type(s)
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/utils/html.py", line 413, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/forms/forms.py", line 537, in __str__
    return self.as_widget()
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/forms/forms.py", line 593, in as_widget
    return force_text(widget.render(name, self.value(), attrs=attrs))
  File "/opt/adagios/venv/lib64/python3.9/site-packages/django/forms/forms.py", line 640, in value
    return self.field.prepare_value(data)
  File "/opt/adagios/adagios/objectbrowser/forms.py", line 180, in prepare_value
    raise ValueError("Expected string. Got %s" % type(value))
ValueError: Expected string. Got <class 'list'>

Can someone give me a tip for solve the problem? thanks in advise

**Comment by gardart** [comment]
Hi, could you try out this fix?
[adagios/objectbrowser/forms.py](https://github.com/opinkerfi/adagios/commit/943f026b98b513772be7a7a5db48223b81d8e76b)

**Comment by lazarobaca** [comment]
It works perfectly! thank you!
